30 feature expandable images with expand icon and slider functionality
cody0-0/jahresprojekt pull request #79
Opened 2024-05-15 18:40 UTC by duevil

**Issue:** #ADD LINK TO GH ISSUE or NOTION

#30 

Clearly and concisely describe the feature.

On Beitrags-page:
- Implemented image overlay with UI elements and caption
- Added expand button to title image
- Added expand icon to inline images and onclick-listener

2024-05-16 12:03 UTC, cody0-0 requested changes
In Light mode
- der Text des IMG-Count-Indicators und der Caption sind fast nicht lesbar
  - die Farbe des Textes ändert sich zwischen dark und light mode, aber die Hintergrund ist dort halt immer dunkel (was ich gut finde) &rarr; die Textfarbe muss hier gleichbleibend sein
<img width="528" alt="image" src="https://github.com/cody0-0/jahresprojekt/assets/113670708/5910f124-b4da-4481-b9d8-40fd33eac6a6">

Warum gibt es einen Unterschied (sowohl visuell als auch funktional) zwischen dem Öffnen eines inline imgs und eines title imgs?
- Position des Icons (unten rechts vs oben rechts)
- visuelle Darstellung (typischer Icon Button vs nur Icon)
- Click-Area (nur Button vs volles img)
- Hatten wir nicht gemeint, es wäre vorzuziehen das immer über einen Button zu machen (v.a. auf Mobile, damit die Gefahr kleiner ist, versehentlich das Bild zu öffnen)?

Wie funktioniert die "slider functionality"? Bei mir werden jedenfalls nicht automatisch die Bilder für den Slider erkannt und der Slider funktioniert nicht. 
- Falls man die Bilder irgendwie dafür kennzeichnen muss, sollte das in der PR stehen.
- Falls das erst später hinzugefügt wird, sollte das in der PR stehen und vor allem nicht im Titel auftauchen.

2024-05-16 13:48 UTC, duevil commented
Hab die Sachen geändert und das mit dem Slider im Kommentar hinzugefügt @cody0-0

2024-05-16 13:57 UTC, cody0-0 requested changes
I mean...

<img width="528" alt="image" src="https://github.com/cody0-0/jahresprojekt/assets/113670708/1b7e7d0d-52a4-4953-9f03-d47fd8cd4d6a">

2024-05-16 13:59 UTC, cody0-0 commented
Wollen wir eigentlich wirklich, dass die Caption centered ist? Sonst ist sie ja immer linksbündig 🤔

2024-05-16 16:06 UTC, duevil commented
> Wollen wir eigentlich wirklich, dass die Caption centered ist? Sonst ist sie ja immer linksbündig 🤔

Aye, ist nervig wegen des Aspect Ratios des Bildes - ich kenn keine reine CSS-Möglichkeit, das linksbündig ans Bild auszurichten, wenn der Container breiter als das Bild ist. Man könnte die natürlich einfach konsequent ganz links stellen

2024-05-16 16:41 UTC, duevil commented
Hoppla, wohl einfach die Caption übersehen

2024-05-17 08:21 UTC, cody0-0 approved these changes
👍 

Caption postion wurde in ein neues Issue ausgelagert - Prio: Niedrig

2024-05-17 08:22 UTC, merged